export enum Type {
    CONCERTI = 'CONCERTI',
    TEATRO = 'TEATRO',
    SPORT = 'SPORT',
    MOSTRA_E_MUSEI = 'MOSTRA_E_MUSEI',
    ALTRE_MANIFESTAZIONI = 'ALTRE_MANIFESTAZIONI',
    EVENTI_INTERNAZIONALI = 'EVENTI_INTERNAZIONALI',
    CINEMA = 'CINEMA'
}